# Generated by Django 3.2.7 on 2021-10-14 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_rename_post_blogcomment_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcomment',
            name='parent',
        ),
        migrations.AddField(
            model_name='blogcomment',
            name='reply',
            field=models.BooleanField(default=False),
        ),
    ]
