# Generated by Django 3.2.7 on 2021-10-15 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_rename_parent_blogcomment_parent_comment_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcomment',
            name='parent_comment_id',
        ),
        migrations.AddField(
            model_name='blogcomment',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.blogcomment'),
        ),
    ]
