# Generated by Django 3.2.7 on 2021-10-15 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_blogpost_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='views_by',
            field=models.CharField(default='', max_length=500),
        ),
    ]
