# Generated by Django 3.2.7 on 2021-10-15 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_blogpost_views_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='views_by',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
